apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-mongo
  namespace: projects
spec:
  serviceName: "blog-mongo-service"
  replicas: 1
  selector:
    matchLabels:
      app: blog-mongo
  template:
    metadata:
      labels:
        app: blog-mongo
    spec:
      containers:
        - name: mongod
          image: mongo:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "root"
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "rootpassword"
            - name: MONGO_INITDB_DATABASE
              value: "blog-website"



