apiVersion: v1
kind: Service
metadata:
  name: blog-frontend-service
  namespace: projects
spec:
  selector:
    app: blog-frontend
  ports:
    - name: http
      port: 3001  # External port
      targetPort: 80  # Internal port
  type: ClusterIP
  #loadBalancerIP: 10.96.0.2  # Static IP from MetalLB