apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: blog-mongo
  namespace: projects
spec:
  serviceName: "blog-mongo-service"
  replicas: 1
  selector:
    matchLabels:
      app: blog-mongo
  template:
    metadata:
      labels:
        app: blog-mongo
    spec:
      containers:
        - name: mongod
          image: mongo:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 27017
          # volumeMounts:
          #   - name: mongo-persistent-storage
          #     mountPath: /mongo-data
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "root"
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "rootpassword"
            - name: MONGO_INITDB_DATABASE
              value: "blog-website"
  # volumeClaimTemplates:
  #   - metadata:
  #       name: mongo-persistent-storage
  #     spec:
  #       accessModes:
  #         - ReadWriteOnce
  #       resources:
  #         requests:
  #           storage: 5Gi


