apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend-app
  ports:
  - protocol: TCP
    port: 80  # External HTTP port
    targetPort: 9000  # Internal port of the frontend container
  type: LoadBalancer  # Exposes the service externally
  # loadBalancerIP: 34.132.41.103