apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      initContainers:
        - name: init-setup
          image: busybox
          command: 
            - /bin/sh
            - -c
            - |
              until nc -zv mysql-service 3306; do
                echo "Waiting for Mysql to be ready..."
                sleep 2
              done
              echo "MySQL is ready, proceeding with application startup."
          imagePullPolicy: IfNotPresent

      containers:
      - name: backend-app
        image: sejaltyagi19/wittyems:B22
        resources:
          requests:
            cpu: 250m  
            memory: 1Gi 
          limits:
            cpu: 500m
            memory: 2Gi
        ports:
        - containerPort: 8080  # Tomcat's port
        env:
        - name: MYSQL_HOST
          value: mysql-service  
        - name: MYSQL_PORT
          value: "3306"  # MySQL default port
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: mysql-configmap
              key: mysql-database
        - name: MYSQL_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-root-username
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-root-password
        # volumeMounts:
        #   - name: log-volume
        #     mountPath: /opt/tomcat/logs  # Ensure this is where your backend app writes logs

      # - name: busybox
      #   image: busybox
      #   command: ["sh", "-c", "tail -f /opt/tomcat/logs/*.log"]
      #   volumeMounts:
      #     - name: log-volume
      #       mountPath: /opt/tomcat/logs

      # volumes:
      # - name: log-volume
      #   # emptyDir: {}
      #   persistentVolumeClaim:
      #     claimName: mysql-logs-pvc  # Ensure this PVC is correctly defined and bound
  