apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "1"
            memory: "1Gi"
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-root-password
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: mysql-configmap
              key: mysql-database
        ports:
        - containerPort: 3306
        # volumeMounts:
        # - name: mysql-storage
        #   mountPath: /var/lib/mysql
        # - name: mysql-storage
        #   mountPath: /var/log/mysql
        # - name: mysql-config
        #   mountPath: /etc/mysql/conf.d 

      - name: sidecar-container
        image: busybox
        command: ["/bin/sh", "-c", "tail -f /var/log/mysql/*.log"]
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
      #   volumeMounts:
      #   - name: mysql-storage
      #     mountPath: /var/log/mysql

      # volumes:
      # - name: mysql-storage
      #   persistentVolumeClaim:
      #     claimName: mysql-pvc
      # - name: mysql-config
      #   configMap:
      #     name: mysql-configmap
      